### ISSUE TITLE
Coal Mines as Iron?

### ISSUE THREAD

**Issue by Oearth** [undefinedthegamebugs/undefinedthegamebugs#12]
I'm unsure what Coal is supposed to look like, but when mining I found a different looking rock that had ferns and plants in it.  I though it was probably Coal, but when mined it said it was Iron, and I had mined some Iron which had a more black look to it.

**Comment by undefinedthegame** [comment]
Hey thanks for the bug report! 

Coal is completely black. The fern one sounds like a bug we have seen when the biome surface material doesn't blend nicely with a surrounding voxel material. Although we can't replicate it reliably as it apparently only happens under certain conditions

**Comment by undefinedthegame** [comment]
Hi,

Coal is completely black. But you can also craft it in the furnace 😊

Cheers,

David Jelen
Lead Developer {Undefined}

FreshMountainStudios
Sebastian-Kneipp-Weg 21
6020 Innsbruck
AT

E-Mail: ***@***.***
Internet: https://undefinedthegame.com/




Von: Oearth
Gesendet: Sonntag, 5. September 2021 22:25
An: undefinedthegame/undefinedthegamebugs
Cc: Subscribed
Betreff: [undefinedthegame/undefinedthegamebugs] Coal Mines as Iron? (#12)

I'm unsure what Coal is supposed to look like, but when mining I found a different looking rock that had ferns and plants in it. I though it was probably Coal, but when mined it said it was Iron, and I had mined some Iron which had a more black look to it.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by undefinedthegame** [comment]
Should be fixed in the next release. Please reeopen if it's not fixed
